<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="NLog" Version="6.0.7" />
        <PackageReference Include="s2protocol.NET" Version="0.9.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TactiX_Localization\TactiX_Localization.csproj" />
        <ProjectReference Include="..\TactiX_Logger\TactiX_Logger.csproj"/>
        <ProjectReference Include="..\TactiX_Models\TactiX_Models.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="SC2ProductionDuration.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
