<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Refit" Version="8.0.0" />
    <PackageReference Include="Refit.Newtonsoft.Json" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tactix_Exception\TactiX_Exception.csproj" />
    <ProjectReference Include="..\TactiX_Models\TactiX_Models.csproj" />
  </ItemGroup>

</Project>
