<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Class1.cs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.3.13" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Resources\Locales\Strings.en-US.axaml" />
      <AdditionalFiles Include="Resources\Locales\Strings.zh-CN.axaml" />
    </ItemGroup>

</Project>
