<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.0" />

    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Markdown.Avalonia.Tight" Version="11.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tactix_Exception\TactiX_Exception.csproj" />
    <ProjectReference Include="..\TactiX_I18N\TactiX_I18N.csproj" />
    <ProjectReference Include="..\TactiX_Logger\TactiX_Logger.csproj" />
    <ProjectReference Include="..\TactiX_Models\TactiX_Models.csproj" />
    <ProjectReference Include="..\Tactix_Network\TactiX_Network.csproj" />
    <ProjectReference Include="..\TactiX_OS_Tools\TactiX_OS_Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\LicenseView.axaml.cs">
      <DependentUpon>LicenseView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Popup\ErrorPopupView.axaml.cs">
      <DependentUpon>ErrorPopupView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
